# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sobel.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sobel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsobel.proto\x12\x05sobel\"5\n\x0cSobelRequest\x12\x12\n\ninput_path\x18\x01 \x01(\t\x12\x11\n\tthreshold\x18\x02 \x01(\x05\"J\n\rSobelResponse\x12\x13\n\x0boutput_path\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x03\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x03\x32I\n\x0cSobelService\x12\x39\n\x0cProcessImage\x12\x13.sobel.SobelRequest\x1a\x14.sobel.SobelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sobel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SOBELREQUEST']._serialized_start=22
  _globals['_SOBELREQUEST']._serialized_end=75
  _globals['_SOBELRESPONSE']._serialized_start=77
  _globals['_SOBELRESPONSE']._serialized_end=151
  _globals['_SOBELSERVICE']._serialized_start=153
  _globals['_SOBELSERVICE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
